version: '3.8'

services:
  app:
    build: .
    container_name: sistema-controle-app
    restart: always
    ports:
      - "3051:80"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - ASAAS_API_KEY=${ASAAS_API_KEY}
      - ASAAS_ENV=${ASAAS_ENV}
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:10.11
    container_name: sistema-controle-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    ports:
      - "3052:3306"
    volumes:
      - db_data:/var/lib/mysql

  waha:
    image: devlikeapro/waha
    container_name: sistema-controle-waha
    restart: always
    environment:
      - WHATSAPP_DEFAULT_ENGINE=NOWEB
      - WAHA_WORKER_ID=sistema-controle
      - WAHA_PRINT_QR=false
      # Otimizações de Memória
      - WAHA_PUPPETEER_ARGS=--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --single-process --disable-gpu
      # Credenciais Fixas
      - WAHA_DASHBOARD_USERNAME=root
      - WAHA_DASHBOARD_PASSWORD=password
      - WHATSAPP_SWAGGER_USERNAME=root
      - WHATSAPP_SWAGGER_PASSWORD=password
      - WAHA_API_KEY=password
    ports:
      - "3050:3000"
    volumes:
      - waha_data:/app/.waha

volumes:
  db_data:
  waha_data:


